# Generated by Django 4.1 on 2023-09-29 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=255, verbose_name='Nombre_Pelicula')),
                ('fecha_streaming', models.DateField(verbose_name='Fecha_Streaming')),
                ('imagen', models.URLField(verbose_name='Imagen')),
                ('critics_score', models.IntegerField(default=0, verbose_name='Critics Score')),
                ('audience_score', models.IntegerField(default=0, verbose_name='Audience Score')),
                ('user_score', models.IntegerField(blank=True, null=True, verbose_name='User Score')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_serie', models.CharField(max_length=255, verbose_name='Nombre_Serie')),
                ('ultimo_capitulo', models.DateField(verbose_name='Ultimo_Capitulo')),
                ('imagen', models.URLField(verbose_name='Imagen_Serie')),
                ('critics_score', models.IntegerField(default=0, verbose_name='Critics Score')),
                ('audience_score', models.IntegerField(default=0, verbose_name='Audience Score')),
                ('user_score', models.IntegerField(blank=True, null=True, verbose_name='User Score')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeliculasVistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peliculas', models.ManyToManyField(blank=True, to='scrapper.pelicula')),
                ('series', models.ManyToManyField(blank=True, to='scrapper.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peliculas', models.ManyToManyField(blank=True, to='scrapper.pelicula')),
                ('series', models.ManyToManyField(blank=True, to='scrapper.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.pelicula')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
