# Generated by Django 4.1 on 2023-09-30 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='streaming',
            field=models.CharField(default=' ', max_length=30, verbose_name='Streaming'),
        ),
        migrations.AddField(
            model_name='serie',
            name='streaming',
            field=models.CharField(default=' ', max_length=30, verbose_name='Streaming'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
