# Generated by Django 4.1 on 2023-10-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_alter_pelicula_imagen_alter_serie_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(max_length=500, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.URLField(max_length=500, null=True, verbose_name='Imagen_Serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ultimo_capitulo',
            field=models.DateField(null=True, verbose_name='Ultimo_Capitulo'),
        ),
    ]
